apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: oldspace
  name: oldspace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oldspace
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: oldspace
    spec:
      containers:
        - image: winja/client_side_debug
          name: oldspace
          ports:
            - containerPort: 80
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
