apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: unoosa
  name: unoosa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: unoosa
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: unoosa
    spec:
      containers:
        - image: winja/flask-session
          name: unoosa
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
