version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    #image: php:8.0-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8001:80
