apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: flaskcache
  name: flaskcache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flaskcache
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: flaskcache
    spec:
      containers:
        - image: winja/flask-cache
          name: flaskcache
          ports:
            - containerPort: 8000
            - containerPort: 5000
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
