apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: satcom
  name: satcom
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: satcom
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: satcom
        outbound: allow
    spec:
      containers:
        - image: winja/websocket
          name: satcom
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
